chsway/config/routes.rb
Chsway::Application.routes.draw do
  devise_for :users

  resources :ideas

  resources :end_users

root :to => "end_users#index"

end

chsway/app/models/end_user.rb
class EndUser < ActiveRecord::Base
  attr_accessible :name, :password
end

chsway/app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :body, :published_at, :title
end

chsway/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

chsway/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

chsway/app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
  # GET /end_users
  # GET /end_users.json
  def index
    @end_users = EndUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @end_users }
    end
  end

  # GET /end_users/1
  # GET /end_users/1.json
  def show
    @end_user = EndUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @end_user }
    end
  end

  # GET /end_users/new
  # GET /end_users/new.json
  def new
    @end_user = EndUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @end_user }
    end
  end

  # GET /end_users/1/edit
  def edit
    @end_user = EndUser.find(params[:id])
  end

  # POST /end_users
  # POST /end_users.json
  def create
    @end_user = EndUser.new(params[:end_user])

    respond_to do |format|
      if @end_user.save
        format.html { redirect_to @end_user, notice: 'End user was successfully created.' }
        format.json { render json: @end_user, status: :created, location: @end_user }
      else
        format.html { render action: "new" }
        format.json { render json: @end_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /end_users/1
  # PUT /end_users/1.json
  def update
    @end_user = EndUser.find(params[:id])

    respond_to do |format|
      if @end_user.update_attributes(params[:end_user])
        format.html { redirect_to @end_user, notice: 'End user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @end_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /end_users/1
  # DELETE /end_users/1.json
  def destroy
    @end_user = EndUser.find(params[:id])
    @end_user.destroy

    respond_to do |format|
      format.html { redirect_to end_users_url }
      format.json { head :no_content }
    end
  end
end

chsway/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

chsway/app/helpers/application_helper.rb
module ApplicationHelper
end

chsway/app/helpers/end_users_helper.rb
module EndUsersHelper
end

chsway/app/helpers/idea_helper.rb
module IdeaHelper
end

chsway/app/helpers/ideas_helper.rb
module IdeasHelper
end

chsway/app/views/end_users/_form.html.erb
<%= form_for(@end_user) do |f| %>
  <% if @end_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@end_user.errors.count, "error") %> prohibited this end_user from being saved:</h2>

      <ul>
      <% @end_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

chsway/app/views/end_users/edit.html.erb
<h1>Editing end_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @end_user %> |
<%= link_to 'Back', end_users_path %>

chsway/app/views/end_users/index.html.erb
<h1>Listing end_users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @end_users.each do |end_user| %>
  <tr>
    <td><%= end_user.name %></td>
    <td><%= end_user.password %></td>
    <td><%= link_to 'Show', end_user %></td>
    <td><%= link_to 'Edit', edit_end_user_path(end_user) %></td>
    <td><%= link_to 'Destroy', end_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New End user', new_end_user_path %>

chsway/app/views/end_users/new.html.erb
<h1>New end_user</h1>

<%= render 'form' %>

<%= link_to 'Back', end_users_path %>

chsway/app/views/end_users/show.html.erb
<% @title = @end_user.name %>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @end_user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @end_user.password %>
</p>


<%= link_to 'Edit', edit_end_user_path(@end_user) %> |
<%= link_to 'Back', end_users_path %>

chsway/app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.text_field :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

chsway/app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

chsway/app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Published at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><%= idea.title %></td>
    <td><%= idea.body %></td>
    <td><%= idea.published_at %></td>
    <td><%= link_to 'Show', idea %></td>
    <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Idea', new_idea_path %>

chsway/app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

chsway/app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @idea.title %>
</p>

<p>
  <b>Body:</b>
  <%= @idea.body %>
</p>

<p>
  <b>Published at:</b>
  <%= @idea.published_at %>
</p>


<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

chsway/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
<%= link_to "Sign up", new_user_registration_path %>
</nav>

<%= yield %>

</body>
</html>